---
- name: Uninstall Google Chrome
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check if Google Chrome is installed
      win_package:
        name: Google Chrome
        state: absent
      register: chrome_uninstall

    - name: Uninstall Google Chrome
      win_package:
        name: Google Chrome
        state: absent
      when: chrome_uninstall.changed
