---
- name: Install 7zip with Chocolatey
  hosts: all
  gather_facts: false

  tasks:
    - name: Install Chocolatey
      win_chocolatey:
        name: chocolatey
        state: present
      delegate_to: localhost
    - name: Install 7zip with Chocolatey
      win_chocolatey:
        name: 7zip
        state: absent
      delegate_to: localhost
