---
- name: Install Rufus on Windows
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Install Chocolatey
      win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

    - name: Install Rufus with Chocolatey
      win_chocolatey:
        name: rufus
        state: present
