---
- name: Uinstall Visual Studio Code on Windows
  hosts: all
  gather_facts:
    timeout: 60
  become: false

  tasks:
    - name: Uinstall Visual Studio Code
      win_chocolatey:
        name: vscode
        state: absent
