- name: Widows machine 
  hosts: all
  gather_facts: true
  become: false

  tasks:
    - name: copy file over to the target
      ansible.windows.win_copy:
        src: /home/fouad/fouad_information
        dest: C:\Users\Fouad\Desktop