---
- name: Uninstall 7-Zip on CentOS Stream 9
  hosts: all
  become: false
  gather_facts: true

  tasks:
    - name: Install Chocolatey
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Uninstall 7-Zip
      win_chocolatey:
        name: 7zip
        state: present
