- name: Widows machine 
  hosts: all
  gather_facts: true
  become: false

  tasks:
    - name: reboot system
      ansible.windows.win_copy:
      src: /home/fouad/fouad_information
      dest: C:\Users\Fouad\Desktop