---
- name: Install Google Chrome on Windows hosts
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install Google Chrome
      chocolatey.chocolatey.win_chocolatey:
        name: googlechrome
        state: present
