---
- name: windows target
  hosts: all
  become: false
  gather_facts: true

---
- name: Install VirtualBox
  hosts: windows
  gather_facts: no

  vars:
    virtualbox_version: "6.1.26"
    virtualbox_install_path: "C:/Program Files/Oracle/VirtualBox"

  tasks:
    - name: Download VirtualBox installer
      win_get_url:
        url: "https://download.virtualbox.org/virtualbox/{{ virtualbox_version }}/VirtualBox-{{ virtualbox_version }}-Win.exe"
        dest: "{{ ansible_env.TEMP }}/VirtualBox-{{ virtualbox_version }}-Win.exe"
      register: download_result

    - name: Install VirtualBox
      win_package:
        path: "{{ download_result.dest }}"
        arguments: "/s"
        product_id: "{D5A0D9B8-D8A2-49E0-9B28-7D209D8B24A6}"
        creates_path: "{{ virtualbox_install_path }}"
      when: download_result.changed
